### ISSUE TITLE
[ERROR] RESERVE KEYWORD ERROR 

### ISSUE THREAD

**Issue by robinreni96** [ScriptSmith/instamancer#19]
/usr/local/lib/node_modules/instamancer/src/cli.js:268
    for await (const post of obj.generator()) {
        ^^^^^

SyntaxError: Unexpected reserved word
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by ScriptSmith** [comment]
I believe you're running an outdated version of Node. Instamancer's package.json recommends Node `>=10.15.0`
