### ISSUE TITLE
[BUG] Redirecting to Instagram login page

### ISSUE THREAD

**Issue by rodrigoangeli** [ScriptSmith/instamancer#40]
I'm trying to run Instamancer on my VPS with CLI but it goes on a loop of sleeping 60s and it doesn't scrap anything.

```
instamancer user therock --count=3 --l="info"
```
And this was the log result:
```
{"message":"Starting API at 1580676295309","level":"info"}
{"level":"error","message":"ErrorNavigation failed because browser has disconnected!","stack":"Error: Navigation failed because browser has disconnected!\n    at CDPSession.<anonymous> (/usr/lib/node_modules/instamancer/node_modules/puppeteer/lib/LifecycleWatcher.js:46:107)\n    at CDPSession.emit (events.js:321:20)\n    at CDPSession._onClosed (/usr/lib/node_modules/instamancer/node_modules/puppeteer/lib/Connection.js:215:10)\n    at Connection._onClose (/usr/lib/node_modules/instamancer/node_modules/puppeteer/lib/Connection.js:138:15)\n    at WebSocket.<anonymous> (/usr/lib/node_modules/instamancer/node_modules/puppeteer/lib/WebSocketTransport.js:48:22)\n    at WebSocket.onClose (/usr/lib/node_modules/instamancer/node_modules/ws/lib/event-target.js:124:16)\n    at WebSocket.emit (events.js:321:20)\n    at WebSocket.emitClose (/usr/lib/node_modules/instamancer/node_modules/ws/lib/websocket.js:191:10)\n    at Socket.socketOnClose (/usr/lib/node_modules/instamancer/node_modules/ws/lib/websocket.js:850:15)\n    at Socket.emit (events.js:321:20)\n  -- ASYNC --\n    at Frame.<anonymous> (/usr/lib/node_modules/instamancer/node_modules/puppeteer/lib/helper.js:111:15)\n    at Page.goto (/usr/lib/node_modules/instamancer/node_modules/puppeteer/lib/Page.js:670:49)\n    at Page.<anonymous> (/usr/lib/node_modules/instamancer/node_modules/puppeteer/lib/helper.js:112:23)\n    at User.constructPage (/usr/lib/node_modules/instamancer/src/api/instagram.js:587:29)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async User.start (/usr/lib/node_modules/instamancer/src/api/instagram.js:222:9)\n    at async spawn (/usr/lib/node_modules/instamancer/src/cli.js:343:5)\n    at async Object.handler (/usr/lib/node_modules/instamancer/src/cli.js:72:9)"}
{"message":"https://instagram.com/therock","level":"error"}
```

I've tried to use the module but it looks like it's redirecting me to Instagram's login page and I've also tried to get on a username's page with Puppeteer but it was also redirecting.

Is this problem IP related maybe? Do you have any experience with these events on Instamancer?

 - OS: Linux - Ubuntu 18.04.4 LTS
 - Instamancer version 3.1.0
 - Node version v13.7.0
 - NPM version 6.13..6

**Comment by ScriptSmith** [comment]
It might be worth using the debug logging level to see if there are any more clues.

My guess would be that your VPS has a limited amount of memory, causing the chrome process to be killed

**Comment by rodrigoangeli** [comment]
Here's the logging.
```
{"message":"Starting API at 1580682529697","level":"info"}
{"message":{"id":"therock","index":0,"sleepRemaining":0,"state":"Launching","total":3},"level":"debug"}
{"message":{"id":"therock","index":0,"sleepRemaining":0,"state":"Navigating","total":3},"level":"debug"}
{"name":"TimeoutError","level":"error","message":"ErrorNavigation timeout of 30000 ms exceeded","stack":"TimeoutError: Navigation timeout of 30000 ms exceeded\n    at /usr/lib/node_modules/instamancer/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21\n  -- ASYNC --\n    at Frame.<anonymous> (/usr/lib/node_modules/instamancer/node_modules/puppeteer/lib/helper.js:111:15)\n    at Page.goto (/usr/lib/node_modules/instamancer/node_modules/puppeteer/lib/Page.js:670:49)\n    at Page.<anonymous> (/usr/lib/node_modules/instamancer/node_modules/puppeteer/lib/helper.js:112:23)\n    at User.constructPage (/usr/lib/node_modules/instamancer/src/api/instagram.js:587:29)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async User.start (/usr/lib/node_modules/instamancer/src/api/instagram.js:222:9)\n    at async spawn (/usr/lib/node_modules/instamancer/src/cli.js:343:5)\n    at async Object.handler (/usr/lib/node_modules/instamancer/src/cli.js:72:9)"}
{"message":"https://instagram.com/therock","level":"error"}
{"message":{"id":"therock","index":0,"sleepRemaining":0,"state":"Request aborted","total":3},"level":"debug"}
{"message":{"id":"therock","index":0,"sleepRemaining":60,"state":"Scraping","total":3},"level":"debug"}
{"message":{"id":"therock","index":0,"sleepRemaining":59,"state":"Scraping","total":3},"level":"debug"}
{"message":{"id":"therock","index":0,"sleepRemaining":58,"state":"Scraping","total":3},"level":"debug"}
{"message":{"id":"therock","index":0,"sleepRemaining":57,"state":"Scraping","total":3},"level":"debug"}
...
{"message":{"id":"therock","index":0,"sleepRemaining":1,"state":"Scraping","total":3},"level":"debug"}
{"message":{"id":"therock","index":0,"sleepRemaining":0,"state":"Scraping","total":3},"level":"debug"}
{"message":{"id":"therock","index":0,"sleepRemaining":0,"state":"Launching","total":3},"level":"debug"}
{"message":{"id":"therock","index":0,"sleepRemaining":0,"state":"Navigating","total":3},"level":"debug"}
{"level":"error","message":"ErrorNavigation failed because browser has disconnected!","stack":"Error: Navigation failed because browser has disconnected!\n    at CDPSession.<anonymous> (/usr/lib/node_modules/instamancer/node_modules/puppeteer/lib/LifecycleWatcher.js:46:107)\n    at CDPSession.emit (events.js:321:20)\n    at CDPSession._onClosed (/usr/lib/node_modules/instamancer/node_modules/puppeteer/lib/Connection.js:215:10)\n    at Connection._onClose (/usr/lib/node_modules/instamancer/node_modules/puppeteer/lib/Connection.js:138:15)\n    at WebSocket.<anonymous> (/usr/lib/node_modules/instamancer/node_modules/puppeteer/lib/WebSocketTransport.js:48:22)\n    at WebSocket.onClose (/usr/lib/node_modules/instamancer/node_modules/ws/lib/event-target.js:124:16)\n    at WebSocket.emit (events.js:321:20)\n    at WebSocket.emitClose (/usr/lib/node_modules/instamancer/node_modules/ws/lib/websocket.js:191:10)\n    at Socket.socketOnClose (/usr/lib/node_modules/instamancer/node_modules/ws/lib/websocket.js:850:15)\n    at Socket.emit (events.js:321:20)\n  -- ASYNC --\n    at Frame.<anonymous> (/usr/lib/node_modules/instamancer/node_modules/puppeteer/lib/helper.js:111:15)\n    at Page.goto (/usr/lib/node_modules/instamancer/node_modules/puppeteer/lib/Page.js:670:49)\n    at Page.<anonymous> (/usr/lib/node_modules/instamancer/node_modules/puppeteer/lib/helper.js:112:23)\n    at User.constructPage (/usr/lib/node_modules/instamancer/src/api/instagram.js:587:29)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async User.constructPage (/usr/lib/node_modules/instamancer/src/api/instagram.js:620:13)\n    at async User.start (/usr/lib/node_modules/instamancer/src/api/instagram.js:222:9)\n    at async spawn (/usr/lib/node_modules/instamancer/src/cli.js:343:5)\n    at async Object.handler (/usr/lib/node_modules/instamancer/src/cli.js:72:9)"}
{"message":"https://instagram.com/therock","level":"error"}
{"message":{"id":"therock","index":0,"sleepRemaining":0,"state":"Request aborted","total":3},"level":"debug"}
{"message":{"id":"therock","index":0,"sleepRemaining":60,"state":"Scraping","total":3},"level":"debug"}
{"message":{"id":"therock","index":0,"sleepRemaining":59,"state":"Scraping","total":3},"level":"debug"}
{"message":{"id":"therock","index":0,"sleepRemaining":58,"state":"Scraping","total":3},"level":"debug"}
...
{"message":{"id":"therock","index":0,"sleepRemaining":3,"state":"Scraping","total":3},"level":"debug"}
{"message":{"id":"therock","index":0,"sleepRemaining":2,"state":"Scraping","total":3},"level":"debug"}
{"message":{"id":"therock","index":0,"sleepRemaining":1,"state":"Scraping","total":3},"level":"debug"}
{"message":{"id":"therock","index":0,"sleepRemaining":0,"state":"Scraping","total":3},"level":"debug"}
```

I've thought about the lack of memory too and built a VM with very similar specs and even worse, sometimes it would take longer but after that it would scrap with no problem.

I think i'm gonna try to upgrade the VPS to test it out

**Comment by rodrigoangeli** [comment]
I've made the upgrade and now the "page crashed" error is gone, but now it's showing the HTML from instagram's login page on the logs.

```
{"message":"Starting API at 1580867364091","level":"info"}
{"message":{"id":"arianagrande","index":0,"sleepRemaining":0,"state":"Launching","total":3},"level":"debug"}
{"message":{"id":"arianagrande","index":0,"sleepRemaining":0,"state":"Navigating","total":3},"level":"debug"}
{"message":{"id":"arianagrande","index":0,"sleepRemaining":0,"state":"Scraping","total":3},"level":"debug"}
{"message":{"id":"arianagrande","index":0,"sleepRemaining":2,"state":"Scraping","total":3},"level":"debug"}
{"message":"Failed: https://www.facebook.com/x/oauth/status?client_id=124024574287414&input_token&origin=1&redirect_uri=https%3A%2F%2Fwww.instagram.com%2Faccounts%2Flogin%2F&sdk=joey&wants_cookie_data=true","level":"info"}
{"message":{"id":"arianagrande","index":0,"sleepRemaining":2,"state":"Request aborted","total":3},"level":"debug"}
{"message":{"id":"arianagrande","index":0,"sleepRemaining":1,"state":"Scraping","total":3},"level":"debug"}
{"message":{"id":"arianagrande","index":0,"sleepRemaining":0,"state":"Scraping","total":3},"level":"debug"}
{"message":{"id":"arianagrande","index":0,"sleepRemaining":2,"state":"Scraping","total":3},"level":"debug"}
{"_type":"warning","_text":"The resource https://www.instagram.com/static/bundles/metro/FBSignupPage.css/8caefd531e0f.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.","_args":[],"_location":{},"level":"info","message":"Console log"}
{"_type":"warning","_text":"The resource https://www.instagram.com/static/bundles/metro/LoginAndSignupPage.css/8acb7a798e78.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.","_args":[],"_location":{},"level":"info","message":"Console log"}
{"message":{"id":"arianagrande","index":0,"sleepRemaining":1,"state":"Scraping","total":3},"level":"debug"}
{"message":{"id":"arianagrande","index":0,"sleepRemaining":0,"state":"Scraping","total":3},"level":"debug"}
{"message":{"id":"arianagrande","index":0,"sleepRemaining":2,"state":"Scraping","total":3},"level":"debug"}
{"message":{"id":"arianagrande","index":0,"sleepRemaining":1,"state":"Scraping","total":3},"level":"debug"}
{"message":{"id":"arianagrande","index":0,"sleepRemaining":2,"state":"Scraping","total":3},"level":"debug"}
{"message":{"id":"arianagrande","index":0,"sleepRemaining":1,"state":"Scraping","total":3},"level":"debug"}
{"message":{"id":"arianagrande","index":0,"sleepRemaining":0,"state":"Scraping","total":3},"level":"debug"}
{"message":{"id":"arianagrande","index":0,"sleepRemaining":2,"state":"Scraping","total":3},"level":"debug"}
{"message":{"id":"arianagrande","index":0,"sleepRemaining":1,"state":"Scraping","total":3},"level":"debug"}
{"message":{"id":"arianagrande","index":0,"sleepRemaining":0,"state":"Scraping","total":3},"level":"debug"}
{"content":"<!DOCTYPE html><html lang=\"en\" class=\"js not-logged-in client-root js-focus-visible sDN5V\"><head>
....
<div class=\"Z2m7o\"><div class=\"CgFia \"></div></div><div id=\"fb-root\" class=\" fb_reset\"><div style=\"position: absolute; top: -10000px; width: 0px; height: 0px;\"><div></div></div></div></body></html>","level":"error","message":"Page failed to make requests"}
{"message":{"id":"arianagrande","index":0,"sleepRemaining":0,"state":"Closing","total":3},"level":"debug"}
```

**Comment by ScriptSmith** [comment]
That's ok. That message should only be appearing because you're looking for a small number of posts, so the page never gets the chance to initiate a request.

**Comment by rodrigoangeli** [comment]
I tried with 50 and unlimited but it didn't work, unfortunately the same messages appeared.

**Comment by ScriptSmith** [comment]
Try adjusting the time spent sleeping between page jumps with `-s20`

**Comment by rodrigoangeli** [comment]
Adjusting the time didn't work either, but I managed to test the module with a proxy and made the  createApi("hashtag") work.

Then I tried to make the same module with createAPI("user") and it didn't work, it looked like it wasn't running the loop (console.log inside wasn't rendering).

Here's what I tried:
```
const options: IOptions = {
	total: 10,
	headless: true,
	proxyURL: '--proxy-server=socks5://127.0.0.1:9050',
};
const user = createApi("user", "therock", options);
const result = [];

(async () => {
	for await (const post of user.generator()) {
		result.push(post)
	}
	fs.writeFileSync('test.json', JSON.stringify(result));
})();
``` 
Changing "user" with "hashtag" works.

**Comment by ScriptSmith** [comment]
Does it work locally? If so, are you using your local connection as the proxy on the VPS?

**Comment by diegofullstackjs** [comment]
where I find the creds.json file?
